- hosts: httpd
  tasks:
          - file:
                  path: "/dvd2"
                  state: directory

          - mount:
                  path: "/dvd2"
                  src: "/dev/cdrom"
                  state: mounted
                  fstype: "iso9660"

          - yum_repository:
                  name: "mydvd1"
                  baseurl: "/dvd2/AppStream"
                  description: "my yum dvd1 for package"
                  gpgcheck: no
 
          - yum_repository:
                  name: "mydvd2"
                  baseurl: "/dvd2/BaseOS"
                  description: "my yum dvd2 for package"
                  gpgcheck: no

          - package:
                  name: "httpd"
                  state: present
         
          - copy:
                  dest: "/var/www/html/index.html"
                  content: "hey this is  new target node server\n"
            notify: Restart required


          - firewalld:
                  port: "80/tcp"
                  state: enabled
                  permanent: yes
                  immediate: yes

  handlers:
  - name: Restart required
    service:
            name: "httpd"
            state: restarted
            enabled: yes


