- hosts: 192.168.0.111
  tasks:
          - file:
                  path: "/dvd2"
                  state: directory

          - mount:
                  path: "/dvd2"
                  src: "/dev/cdrom"
                  state: mounted
                  fstype: "iso9660"
  
          - name: "configuring yum repo for AppStream"
            yum_repository:
                  name: "mydvd1"
                  baseurl: "/dvd2/AppStream"
                  description: "my yum dvd1 for package"
                  gpgcheck: no
 
          - name: "configuring yum repo for BaseOS"
            yum_repository:
                  name: "mydvd2"
                  baseurl: "/dvd2/BaseOS"
                  description: "my yum dvd2 for package"
                  gpgcheck: no


          - name: "configuring yum repository for docker"
            yum_repository:
                  name: "docker"
                  description: "repository for docker software"
                  baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable/"
                  gpgcheck: no

          - name: "Installing docker community edititon"
            package:
                    name: "docker-ce-18.09.1-3.el7.x86_64"
                    state: present

          - name: "starting docker services in the Target node"
            service:
                    name: docker
                    state: started

          - name: "Instaling python3.6"
            package: 
                    name: "python36"
                    state: present
          
          - name: "Installing docker dependecy using pip"
            pip:
                    name: "docker"
                    state: present
            
          - name: "Pulling httpd docker container image from docker hub"
            docker_image:
                    name: httpd
                    source: pull
                    tag: latest

          - name: "Creating a folder where we will keep all of our webpage"
            file:
                    path: "/doc-webpage"
                    state: directory

          - name: "Copying file from Controller node to Target node"
            copy:
                    src: "web.html"
                    dest: "/doc-webpage/index.html"

          - name: "Launching a docker container with httpd image"
            docker_container:
                    name: "webserver"
                    image: httpd
                    state: started
                    exposed_ports: "80"
                    ports: "8080:80"
                    volumes: "/doc-webpage/:/usr/local/apache2/htdocs"
                    network_mode: bridge

          - name: "Allowing masqueradec from firewall"
            firewalld:
                    masquerade: yes
                    zone: public
                    state: enabled
                    permanent: yes
                    immediate: yes


