- hosts: dynamic_server
  vars_files:
          - "{{ ansible_facts['distribution'] }}{{ ansible_facts['distribution_major_version'] }}.yml"

  tasks:
          - name: Installing webserver
            package:
                    name: "{{ package_name }}"
                    state: present

          - name: Copying the webpages
            template:
                    src: index.html
                    dest: "{{ document_root_location }}"

          - name: Starting the services
            service:
                    name: "{{ package_name }}"
                    state: started
          
